[project]
name = "zero-verse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning>=2.5.2",
    "optuna>=4.4.0",
    "pettingzoo[classic]>=1.25.0",
    "pyyaml>=6.0.2",
    "torch>=2.8.0",
    "wandb>=0.21.1",
]
